### ISSUE TITLE
the website showed my ip

### ISSUE THREAD

**Issue by watameln** [WaviestBalloon/MyNameIsWalterHartwellWhite#4]
it showed my ip this is a ip logger!!

**Comment by WaviestBalloon** [comment]
ok

**Comment by AlekEagle** [comment]
sad

**Comment by WaviestBalloon** [comment]
D:

**Comment by watameln** [comment]
😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭

**Comment by WaviestBalloon** [comment]
This should now be fixed by https://github.com/WaviestBalloon/MyNameIsWalterHartwellWhite/commit/be95668144000c20e9e618a294985f080602d8ef

**Comment by watameln** [comment]
how do i unsubscribe to emails

**Comment by WaviestBalloon** [comment]
You don't
